// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportsBookingAPI.Data;

#nullable disable

namespace SportsBookingAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260813123038_RenameGradoviToCities")]
    partial class RenameGradoviToCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SportsBookingAPI.Models.AppNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MembershipId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguagePreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("bs");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SportsBookingAPI.Models.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("City", "SportType");

                    b.ToTable("Arenas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Patriotske lige 41, Sarajevo",
                            City = "Sarajevo",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Otvoreni teren smješten tik uz gradske saobraćajnice i nekoliko kafića, pa je pogodan za rekreativne i takmičarske termine. Reflektori pružaju vrlo dobro večernje osvjetljenje, a teren se redovno održava tokom cijele sezone. Na raspolaganju su svlačionice, manji tribinski prostor i parking u neposrednoj blizini.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20modern%20outdoor%20football%20arena%20in%20Sarajevo%2C%20Balkan%20sports%20center%20architecture%2C%20empty%20artificial%20turf%20field%2C%20stadium%20lights%2C%20small%20seating%20area%2C%20fences%2C%20evening%20atmosphere%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1001&model=flux&nologo=true&private=true",
                            Name = "Arena Koševo Center",
                            PricePerHour = 50m,
                            SportType = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Terezija bb, Sarajevo",
                            City = "Sarajevo",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Moderna dvorana sa parketom pogodnim za treninge klubova, škola košarke i rekreativne mečeve. Unutrašnji prostor je dobro ventilisan, a gledalište omogućava ugodno praćenje utakmica za manju publiku. U objektu se nalaze svlačionice, sanitarni čvorovi i recepcijski prostor.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20indoor%20basketball%20hall%20in%20Sarajevo%2C%20modern%20European%20sports%20facility%2C%20polished%20wooden%20court%2C%20seating%20stands%2C%20ceiling%20lights%2C%20empty%20arena%2C%20realistic%20architecture%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1002&model=flux&nologo=true&private=true",
                            Name = "Skenderija Basket Hall",
                            PricePerHour = 42m,
                            SportType = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Fra Anđela Zvizdovića 8, Sarajevo",
                            City = "Sarajevo",
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Padel centar otvorenog tipa sa kvalitetnom podlogom i zaštitnim staklenim panelima koji dobro drže ritam igre. Arena ima večernju rasvjetu, rezervisana parking mjesta i lounge zonu za odmor između termina. Lokacija je praktična za dolazak iz više dijelova grada.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20outdoor%20padel%20court%20complex%20in%20Sarajevo%2C%20glass%20walls%2C%20modern%20Balkan%20sports%20center%2C%20evening%20lighting%2C%20spectator%20benches%2C%20fenced%20courts%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1003&model=flux&nologo=true&private=true",
                            Name = "Padel Vista Marijin Dvor",
                            PricePerHour = 36m,
                            SportType = "Padel"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Maršala Tita 178, Mostar",
                            City = "Mostar",
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Otvoreni nogometni kompleks s prirodnim osjećajem terena i uredno obilježenim linijama za rekreativne lige. Prostor je osvijetljen za večernje termine, a uz teren se nalazi nekoliko klupa i manja natkrivena zona za gledaoce. Arena je posebno popularna među ekipama koje žele termin u mirnijem dijelu grada.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20outdoor%20football%20sports%20park%20in%20Mostar%2C%20Balkan%20urban%20setting%2C%20green%20field%2C%20floodlights%2C%20fences%2C%20modest%20grandstand%2C%20warm%20stone%20architecture%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1004&model=flux&nologo=true&private=true",
                            Name = "Velež Sport Park",
                            PricePerHour = 50m,
                            SportType = "Football"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kneza Branimira 12, Mostar",
                            City = "Mostar",
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zatvorena košarkaška dvorana sa stabilnom rasvjetom i vrlo dobrim akustičnim uslovima za trening i turnire. Parket je redovno održavan, a uz salu su dostupne svlačionice, tuševi i manja tribina. U blizini se nalaze parking mjesta i nekoliko ugostiteljskih objekata.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20indoor%20basketball%20arena%20in%20Mostar%2C%20modern%20sports%20hall%2C%20hardwood%20court%2C%20bright%20roof%20lighting%2C%20compact%20spectator%20area%2C%20clean%20European%20design%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1005&model=flux&nologo=true&private=true",
                            Name = "Neretva Basket House",
                            PricePerHour = 42m,
                            SportType = "Basketball"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Bulevar narodne revolucije 21, Mostar",
                            City = "Mostar",
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mirniji padel kompleks smješten nedaleko od gradskog jezgra, idealan za rekreativce i manje turnire. Tereni su na otvorenom, imaju snažno noćno osvjetljenje i dovoljno prostora oko staklenih ograda za sigurnu igru. Gostima su na raspolaganju parking, svlačionice i terasa za odmor.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20outdoor%20padel%20club%20in%20Mostar%2C%20glass%20padel%20courts%2C%20Mediterranean%20Balkan%20atmosphere%2C%20modern%20lighting%2C%20lounge%20terrace%2C%20clean%20fences%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1006&model=flux&nologo=true&private=true",
                            Name = "Padel Club Buna",
                            PricePerHour = 36m,
                            SportType = "Padel"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Rudarska 2, Tuzla",
                            City = "Tuzla",
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nogometni teren sa umjetnom travom projektovan za dinamične termine malog fudbala i treninge mlađih selekcija. Reflektori pokrivaju čitavu površinu, a pored terena postoji dovoljno prostora za zagrijavanje i kratki odmor. Kompleks nudi svlačionice, parking i pristup glavnim gradskim saobraćajnicama.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20small%20football%20arena%20in%20Tuzla%2C%20empty%20synthetic%20turf%20field%2C%20floodlights%2C%20fences%2C%20parking%20nearby%2C%20modern%20Bosnian%20sports%20facility%2C%20overcast%20daylight%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1007&model=flux&nologo=true&private=true",
                            Name = "Tušanj Arena 5+",
                            PricePerHour = 50m,
                            SportType = "Football"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Bosne Srebrene 55, Tuzla",
                            City = "Tuzla",
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Višenamjenska dvorana sa kvalitetnim parketom i odličnom preglednošću terena iz gledališta. Prostor je pogodan za treninge, prijateljske utakmice i školske turnire, uz uredne svlačionice i pomoćne prostorije. Lokacija u sportskom centru olakšava pristup i organizaciju događaja.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20indoor%20basketball%20sports%20hall%20in%20Tuzla%2C%20clean%20wooden%20court%2C%20bright%20lighting%2C%20tiered%20seating%2C%20modern%20Balkan%20civic%20arena%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1008&model=flux&nologo=true&private=true",
                            Name = "Mejdan Basket Arena",
                            PricePerHour = 42m,
                            SportType = "Basketball"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Šetalište Slana banja 18, Tuzla",
                            City = "Tuzla",
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Padel teren u modernom rekreativnom kompleksu, poznat po urednoj podlozi i prijatnom ambijentu tokom cijelog dana. Reflektori omogućavaju stabilnu igru i u kasnijim večernjim satima, a gostima su dostupni garderoberi i caffe zona. Posebna prednost je blizina parkinga i centra grada.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20outdoor%20padel%20arena%20in%20Tuzla%2C%20modern%20glass%20courts%2C%20evening%20lights%2C%20urban%20recreational%20zone%2C%20fenced%20facility%2C%20empty%20courts%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1009&model=flux&nologo=true&private=true",
                            Name = "Padel Panonika",
                            PricePerHour = 36m,
                            SportType = "Padel"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Kralja Petra I Karađorđevića 91, Banja Luka",
                            City = "Banja Luka",
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Otvorena arena za mali fudbal sa čvrstom umjetnom travom i vrlo dobrom drenažom nakon kiše. Teren je osvijetljen, ograda je uredna i sigurna, a uz objekat se nalaze svlačionice i prostor za kraće zadržavanje ekipa. Arena često okuplja rekreativne lige i vikend turnire.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20football%20hub%20in%20Banja%20Luka%2C%20empty%20artificial%20grass%20pitch%2C%20European%20sports%20facility%2C%20perimeter%20fences%2C%20floodlights%2C%20modest%20stands%2C%20modern%20architecture%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1010&model=flux&nologo=true&private=true",
                            Name = "Krajina Football Hub",
                            PricePerHour = 50m,
                            SportType = "Football"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Aleja Svetog Save 48, Banja Luka",
                            City = "Banja Luka",
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Košarkaška dvorana poznata po ravnomjernom osvjetljenju i dobro održavanom parketu koji odgovara i intenzivnijim treninzima. U sklopu objekta nalaze se svlačionice, prostor za trenere i manja zona za gledaoce. U neposrednoj blizini postoji više parking mjesta i pristup glavnim ulicama.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20indoor%20basketball%20court%20in%20Banja%20Luka%2C%20bright%20sports%20hall%20lighting%2C%20polished%20parquet%2C%20spectator%20seating%2C%20contemporary%20Balkan%20arena%20interior%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1011&model=flux&nologo=true&private=true",
                            Name = "Borik Basket Zone",
                            PricePerHour = 42m,
                            SportType = "Basketball"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Cara Lazara 77, Banja Luka",
                            City = "Banja Luka",
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Padel centar sa otvorenim terenima i prijatnim ambijentom uz rijeku, što ga čini popularnim za popodnevne i večernje termine. Podloga je brza, staklene ograde su kvalitetne, a osvjetljenje ravnomjerno raspoređeno. Gosti imaju pristup parkingu, garderoberima i zoni za osvježenje.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20outdoor%20padel%20complex%20near%20river%20in%20Banja%20Luka%2C%20modern%20glass%20courts%2C%20elegant%20lighting%2C%20landscaped%20sports%20center%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1012&model=flux&nologo=true&private=true",
                            Name = "Padel Riverside Vrbas",
                            PricePerHour = 36m,
                            SportType = "Padel"
                        },
                        new
                        {
                            Id = 13,
                            Address = "5. korpusa 14, Bihać",
                            City = "Bihać",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nogometni teren u mirnijem dijelu Bihaća, pogodan za termine prijateljskih ekipa i školskih sekcija. Reflektori pružaju dobru vidljivost, a uz teren postoje klupe za igrače i mali prostor za gledaoce. Površina terena je uredna i pogodna za cjelogodišnje korištenje.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20outdoor%20football%20terrain%20in%20Bihac%2C%20empty%20field%2C%20fences%2C%20tribune%20benches%2C%20clean%20Balkan%20sports%20center%2C%20natural%20daylight%2C%20parking%20and%20trees%20nearby%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1013&model=flux&nologo=true&private=true",
                            Name = "Una Football Point",
                            PricePerHour = 50m,
                            SportType = "Football"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Harmanski sokak 9, Bihać",
                            City = "Bihać",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zatvoreni košarkaški prostor sa ugodnom atmosferom i parketom koji dobro podnosi česte treninge. Arena je pogodna za omladinske selekcije i rekreativne mečeve, uz svlačionice i pristojan prostor za publiku. Lokacija je lako dostupna i u blizini ima dovoljno parking mjesta.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20indoor%20basketball%20hall%20in%20Bihac%2C%20hardwood%20court%2C%20bright%20ceiling%20lighting%2C%20modest%20stands%2C%20local%20European%20sports%20facility%2C%20empty%20arena%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1014&model=flux&nologo=true&private=true",
                            Name = "Dvorana Sokol Basket",
                            PricePerHour = 42m,
                            SportType = "Basketball"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Bedem 23, Bihać",
                            City = "Bihać",
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Otvoreni padel kompleks sa čistim linijama terena i dobro održavanom podlogom za rekreativnu i takmičarsku igru. Prostor ima rasvjetu za noćne termine, svlačionice i manji lounge kutak za ekipe nakon meča. Blizina zelenih zona daje cijelom centru opušten i prijatan dojam.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20outdoor%20padel%20gardens%20in%20Bihac%2C%20glass%20wall%20courts%2C%20green%20surroundings%2C%20evening%20lights%2C%20modern%20recreational%20center%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1015&model=flux&nologo=true&private=true",
                            Name = "Padel Una Gardens",
                            PricePerHour = 36m,
                            SportType = "Padel"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Bulevar Kralja Tvrtka I 6, Zenica",
                            City = "Zenica",
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arena za mali fudbal sa kvalitetnom umjetnom travom i vrlo dobrom preglednošću cijele površine. Reflektori i zaštitna ograda omogućavaju sigurne večernje termine, a u sklopu centra nalaze se svlačionice i parking. Često je izbor ekipa koje traže centralnu lokaciju u Zenici.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20football%20arena%20in%20Zenica%2C%20empty%20artificial%20turf%2C%20powerful%20floodlights%2C%20fences%2C%20compact%20stands%2C%20urban%20Balkan%20sports%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1016&model=flux&nologo=true&private=true",
                            Name = "Bilino Football Arena",
                            PricePerHour = 50m,
                            SportType = "Football"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Prve zeničke brigade 3, Zenica",
                            City = "Zenica",
                            CreatedAt = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unutrašnja dvorana sa profesionalnim osjećajem prostora, pogodna za treninge klubova i rekreativne utakmice. Parket je u dobrom stanju, rasvjeta je ravnomjerna, a manja tribina omogućava prisustvo publike bez gužve. Korisnicima su dostupne svlačionice, sanitarni čvorovi i prateći sadržaji.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20indoor%20basketball%20arena%20in%20Zenica%2C%20polished%20wood%20floor%2C%20balanced%20lighting%2C%20spectator%20tribune%2C%20contemporary%20European%20sports%20hall%2C%20empty%20facility%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1017&model=flux&nologo=true&private=true",
                            Name = "Arena Kamberovića Basket",
                            PricePerHour = 42m,
                            SportType = "Basketball"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Londža 41, Zenica",
                            City = "Zenica",
                            CreatedAt = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Savremeni padel teren sa urednim staklenim panelima, kvalitetnim osvjetljenjem i dovoljno prostora oko terena za udobno kretanje igrača. Centar je pogodan i za početnike i za naprednije rekreativce, a uz teren se nalaze parking i zona za odmor. Atmosfera je mirna, ali dovoljno živahna za turnirske dane.",
                            ImageUrl = "https://image.pollinations.ai/prompt/photorealistic%20modern%20padel%20center%20in%20Zenica%2C%20empty%20glass%20courts%2C%20evening%20lights%2C%20fences%2C%20sleek%20Balkan%20sports%20architecture%2C%20realistic%20facility%20atmosphere%2C%20no%20players%2C%20no%20logos?width=1280&height=720&seed=1018&model=flux&nologo=true&private=true",
                            Name = "Padel City Zen",
                            PricePerHour = 36m,
                            SportType = "Padel"
                        });
                });

            modelBuilder.Entity("SportsBookingAPI.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.FavoriteArena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArenaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("UserId", "ArenaId")
                        .IsUnique();

                    b.ToTable("FavoriteArenas");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KategorijaSporta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupChatReadState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupChatReadStates");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("GroupMessages");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMessageReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupMessageId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMessageReactions");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMessageReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupMessageId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMessageReceipts");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateChatReadState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("PrivateChatReadStates");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserOneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserTwoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserTwoId");

                    b.HasIndex("UserOneId", "UserTwoId")
                        .IsUnique();

                    b.ToTable("PrivateConversations");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("PrivateMessages");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateMessageReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrivateMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PrivateMessageId", "UserId")
                        .IsUnique();

                    b.ToTable("PrivateMessageReactions");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArenaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ArenaId", "StartTime")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsBookingAPI.Models.AppNotification", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.AppUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsBookingAPI.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsBookingAPI.Models.GroupMembership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportsBookingAPI.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Group");

                    b.Navigation("Membership");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.FavoriteArena", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arena");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.Group", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.AppUser", "Admin")
                        .WithMany("Groups")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupChatReadState", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMembership", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.Group", "group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("group");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMessage", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.Group", "Group")
                        .WithMany("GroupMessages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.GroupMessage", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsBookingAPI.Models.AppUser", "SenderUser")
                        .WithMany("GroupMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMessageReaction", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.GroupMessage", "GroupMessage")
                        .WithMany("Reactions")
                        .HasForeignKey("GroupMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMessageReceipt", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.GroupMessage", "GroupMessage")
                        .WithMany("Receipts")
                        .HasForeignKey("GroupMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany("GroupMessageReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateChatReadState", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.PrivateConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany("PrivateChatReadStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateConversation", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.AppUser", "UserOne")
                        .WithMany("PrivateConversationsAsUserOne")
                        .HasForeignKey("UserOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "UserTwo")
                        .WithMany("PrivateConversationsAsUserTwo")
                        .HasForeignKey("UserTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserOne");

                    b.Navigation("UserTwo");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateMessage", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.PrivateConversation", "Conversation")
                        .WithMany("PrivateMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.PrivateMessage", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsBookingAPI.Models.AppUser", "SenderUser")
                        .WithMany("PrivateMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateMessageReaction", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.PrivateMessage", "PrivateMessage")
                        .WithMany("Reactions")
                        .HasForeignKey("PrivateMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrivateMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.Reservation", b =>
                {
                    b.HasOne("SportsBookingAPI.Models.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBookingAPI.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arena");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.AppUser", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("GroupMessageReceipts");

                    b.Navigation("GroupMessages");

                    b.Navigation("Groups");

                    b.Navigation("Notifications");

                    b.Navigation("PrivateChatReadStates");

                    b.Navigation("PrivateConversationsAsUserOne");

                    b.Navigation("PrivateConversationsAsUserTwo");

                    b.Navigation("PrivateMessages");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.Group", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.GroupMessage", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateConversation", b =>
                {
                    b.Navigation("PrivateMessages");
                });

            modelBuilder.Entity("SportsBookingAPI.Models.PrivateMessage", b =>
                {
                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
